import React, { useState } from 'react';

export default function ImageMessage({ src, alt = 'Generated by Nexus' }) {
  const [loaded, setLoaded] = useState(false);
  const [failed, setFailed] = useState(false);

  if (failed) {
    return <div className="glass-card-sm p-3 text-danger">Image failed to load.</div>;
  }

  return (
    <figure className="mb-0">
      {!loaded ? <div className="skeleton mb-2" style={{ height: 220 }} /> : null}
      <img
        alt={alt}
        className="generated-image"
        onClick={() => window.open(src, '_blank', 'noopener,noreferrer')}
        onError={() => setFailed(true)}
        onLoad={() => setLoaded(true)}
        src={src}
        style={{ cursor: 'zoom-in', display: loaded ? 'block' : 'none' }}
      />
      <figcaption className="text-secondary small mt-2">Generated by Nexus</figcaption>
    </figure>
  );
}
